DBMS_WebApp/myproject/lib/urls.py
from django.urls import path

from . import views
app_name='lib'
urlpatterns = [
	path('',views.index , name='index'),
    path('home/', views.home, name='home'),
    #path('login/', views.login, name='login'),

    path('userlogin/', views.userlogin, name='userlogin'),
    path('adminlogin/', views.adminlogin, name='adminlogin'),

    path('adminlogout/', views.adminlogout, name='adminlogout'),
    path('userlogout/', views.userlogout, name='userlogout'),

    path('submitbook/',views.submitbook, name='submitbook'),
    path('issuebook/',views.issuebook, name='issuebook'),

    path('searchbooks/', views.searchbooks, name='searchbooks'),
    path('signup/', views.signup, name='signup'),
    path('main/', views.main, name='main'),
    path('mainuser/', views.mainuser, name='mainuser'),
    path('mainadmin/', views.mainadmin, name='mainadmin'),

    path('updateprofile/', views.updateprofile, name='updateprofile'),
    path('updateprofiler/', views.updateprofiler, name='updateprofiler'),
    path('chpwd/', views.chpwd, name='chpwd'),

    path('add_author/', views.add_author, name='add_author'),
    path('add_book/', views.add_book, name='add_book'),
    path('add_publisher/', views.add_publisher, name='add_publisher'),
    path('add_section/', views.add_section, name='add_section'),
    path('add_admin/', views.add_admin, name='add_admin'),
    path('add_properbooks/', views.add_properbooks, name='add_properbooks'),

    path('show_authors/', views.show_authors, name='show_authors'),
    path('show_books/', views.show_books, name='show_books'),
    path('show_publishers/', views.show_publishers, name='show_publishers'),
    path('show_readers/', views.show_readers, name='show_readers'),
    path('show_sections/', views.show_sections, name='show_sections'),
    path('show_admins/', views.show_admins, name='show_admins'),

    path('submitbook/', views.submitbook, name='submitbook'),
    path('issuebook/', views.issuebook, name='issuebook'),


]

DBMS_WebApp/myproject/myproject/urls.py
from django.contrib import admin
#from django.conf.urls import include, url
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lib/', include('lib.urls')),
]

DBMS_WebApp/myproject/lib/models.py
import datetime
from django.db import models
from django.utils import timezone

DBMS_WebApp/myproject/lib/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from django.http import Http404
from django.views import generic
from django.utils import timezone

import mysql.connector
mydb = mysql.connector.connect(
	host="localhost",
	user="root",
	password="loop",
	database="test"
)
cursor = mydb.cursor()

def likelist(t):
	l=[]
	for i in t:
		l.append('%%%s%%'%i)
	return l

def index(request):
	return redirect('lib:home')

def userlogin(request):
	if(request.method=="POST"):
		username=request.POST['username']
		password=request.POST['password']
		sql="select rid,name from readers where username =%s and password =%s"
		arg=(username,password,)
		cursor.execute(sql,(username,password,))
		result = cursor.fetchall()
		if(len(result)>0):
			request.session['rid']=result[0][0]
			request.session['uname']=result[0][1]
			return redirect('lib:mainuser')
		else:
			return render(request,'lib/userlogin.html',{'ismached':False})
	else:
		return render(request,'lib/userlogin.html',{'ismached':True})
def adminlogin(request):
	if(request.method=="POST"):
		username=request.POST['username']
		password=request.POST['password']
		sql="select adid from admins where username =%s and password =%s"
		arg=(username,password,)
		cursor.execute(sql,(username,password,))
		result = cursor.fetchall()
		if(len(result)>0):
			request.session['adid']=result[0][0]
			return redirect('lib:mainadmin')
		else:
			return render(request,'lib/adminlogin.html',{'ismached':False})
	else:
		return render(request,'lib/adminlogin.html',{'ismached':True})
def searchbooks(request):
	try:
		bid=request.GET['bid']
		bname=request.GET['bname']
		category=request.GET['category']
		auth=request.GET.get('auth')
		publisher=request.GET.get('publisher')

		sql="""select bid,books.name as bname,category,authors.name as aname,publishers.name as pname,copies_total - copies_assigned as copiesleft
		from books,authors,publishers where bid like %s  and  books.name like %s  and category like %s and publisher=pid and publishers.name like %s and authors.name in 
		(select name from authors natural inner join books_authors where name like %s and books.bid = books_authors.bid)"""
		cursor.execute(sql,likelist((bid,bname,category,auth,publisher,)))
		result = cursor.fetchall()
		
		return render(request,'lib/searchbooks.html',{'result':result})
	except:	
		print("In Except of searchbooks")
		return render(request,'lib/searchbooks.html',{'result':{}})
def signup(request):
	if (request.method == 'POST'):
		username=request.POST.get('username')
		password=request.POST.get('pwd')
		cpassword=request.POST.get('cpwd')
		print(request.POST.get('dob'))
		isusernameempty=False
		passmatch=True
		isuserexist=False
		if(username==''):
			isusernameempty=True
		if(password!=cpassword):
			passmatch=False
		sql='select username from readers where username=%s'
		cursor.execute(sql,(username,))
		result = cursor.fetchall()
		data={}
		for x in result:
			if username in x:
				isuserexist=True
		if(isuserexist or not passmatch or isusernameempty):
			return render(request,'lib/signupr.html',{'isuserexist':isuserexist,'passmatch':passmatch,'isusernameempty':isusernameempty})
		else:
			sql='''insert into readers (username, password ,name,dob,email,phone0,phone1,
			addr,city,pin,no_of_books_assigned,due_fine) values (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,0,0)'''
			argus=(request.POST['username'],request.POST['pwd'],request.POST['name'],request.POST['dob'],\
				request.POST['email'],request.POST['phone0'],request.POST['phone1'],request.POST['addr'],request.POST['city'],request.POST['pin'],)
			cursor.execute(sql,argus)
			print('Checkpoint')
			mydb.commit()
			sql='select rid,name from readers where username =%s'
			cursor.execute(sql,(username,))
			result = cursor.fetchall()
			request.session['rid']=result[0][0]
			request.session['uname']=result[0][1]
			print(result[0][0])
			return redirect('lib:mainuser')

	return render(request,'lib/signup.html',)

def onlyadmin(func):
	def ofunc(req):
		if('adid' in req.session):
			return func(req)
		else:
			return redirect('lib:adminlogin')
	return ofunc

@onlyadmin
def mainadmin(request):
	return render(request,'lib/mainadmin.html')

def mainuser(request):
	print("In mainuser")
	if('rid' in request.session):
		return render(request,'lib/mainuser.html')
	else: return redirect('lib/login')

def updateprofile(request):
	try:
		rid=request.session['rid']
		sql='select name,username,dob,email,phone0,phone1,addr,city,pin from readers where rid = %s'
		cursor.execute(sql,(rid,))
		result = cursor.fetchall()
		userdata={}
		if(len(result)>0):
			userdata['name']=result[0][0]
			userdata['username']=result[0][1]
			userdata['dob']=result[0][2]
			userdata['email']=result[0][3]
			userdata['phone0']=result[0][4]
			userdata['phone1']=result[0][5]
			userdata['addr']=result[0][6]
			userdata['city']=result[0][7]
			userdata['pin']=result[0][8]
		return render(request,'lib/updateprofile.html',{'userdata':userdata})
	except:
		print("In Except of updateprofile")
		return redirect(request,'lib:home')
def updateprofiler(request):
	print("Entered updateprofiler")
	try:
		rid=request.session['rid']
		print('Checkpoint0')
		sql='update readers SET name=%s,username=%s,dob=%s,email=%s,phone0=%s,phone1=%s,addr=%s,city=%s,pin=%s where rid = %s'
		arg=(request.POST['name'],request.POST['username'],request.POST['dob'],request.POST['email'],request.POST['phone0'],request.POST['phone1'],request.POST['addr'],request.POST['city'],request.POST['pin'],rid,)
		print(arg)
		cursor.execute(sql,arg)
		print('Checkpoint')
		mydb.commit()
	except:
		print("In Except of updateprofiler")
	return redirect('lib:mainuser')

def chpwd(request):
	if(request.method=="POST"):
		if(request.POST['pwd']==request.POST['cpwd']):
			sql='update readers SET password=%s where rid = %s'
			arg=(request.POST['pwd'],request.session['rid'],)
			cursor.execute(sql,arg)
			mydb.commit()
			return redirect('lib:mainuser')
		else:
			return render(request,'lib/chpwd.html',{'passmatch':False})
	return render(request,'lib/chpwd.html',{'passmatch':True})

def main(request):
	myresult=[[100,200,300]]
	
	return render(request,'lib/main.html',{'data':myresult})

def home(request):
	return render(request,'lib/home.html',{})

def userlogout(request):
	try:
		del(request.session['rid'])
		return redirect('lib:userlogin')
	except:
		return redirect('lib:userlogin')

def adminlogout(request):
	try:
		del(request.session['adid'])
		return redirect('lib:adminlogin')
	except:
		return redirect('lib:adminlogin')

@onlyadmin
def add_author(request):
	if(request.method=="POST"):
		sql='insert into authors (name,dob,email,phone0,phone1,addr,city,pin) values (%s,%s,%s,%s,%s,%s,%s,%s)'
		arg=(request.POST['name'],request.POST['dob'],\
		request.POST['email'],request.POST['phone0'],request.POST['phone1'],request.POST['addr'],request.POST['city'],request.POST['pin'],)
		cursor.execute(sql,arg)
		mydb.commit()
		return redirect('lib:mainadmin')
	else:
		return render(request,'lib/add_author.html')

@onlyadmin
def add_book(request):
	if(request.method=="POST"):
		sql='insert into books (name,category,publisher,copies_total,copies_assigned) values (%s,%s,%s,%s,0)'
		arg=(request.POST['name'],request.POST['category'],request.POST['publisher'],request.POST['copies_total'],)
		cursor.execute(sql,arg)
		mydb.commit()
		return redirect('lib:mainadmin')
	else:
		return render(request,'lib/add_book.html')

@onlyadmin
def add_publisher(request):
	if(request.method=="POST"):
		sql='insert into publishers (name,email,phone0,phone1,addr,city,pin) values (%s,%s,%s,%s,%s,%s,%s)'
		arg=(request.POST['name'],request.POST['email'],request.POST['phone0'],request.POST['phone1'],request.POST['addr'],request.POST['city'],request.POST['pin'],)
		cursor.execute(sql,arg)
		mydb.commit()
		return redirect('lib:mainadmin')
	else:	
		return render(request,'lib/add_publisher.html')

@onlyadmin
def add_section(request):
	if(request.method=="POST"):
		sql='insert into sections (name,room_no,category) values (%s,%s,%s)'
		arg=(request.POST['name'],request.POST['room_no'],request.POST['category'],)
		cursor.execute(sql,arg)
		mydb.commit()
		return redirect('lib:mainadmin')
	else:	
		return render(request,'lib/add_section.html')

@onlyadmin
def add_admin(request):
	if(request.method=="POST"):
		if(request.POST['pwd']==request.POST['cpwd']):
			sql='insert into admins (name,username,password,post,salary,dob,email,phone0,phone1,addr,city,pin) values (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)'
			arg=(request.POST['name'],request.POST['username'],request.POST['pwd'],request.POST['post'],request.POST['salary'],request.POST['dob'],\
			request.POST['email'],request.POST['phone0'],request.POST['phone1'],request.POST['addr'],request.POST['city'],request.POST['pin'],)
			cursor.execute(sql,arg)
			mydb.commit()
			return redirect('lib:mainadmin')
		else:
			return render(request,'lib/add_admin.html' ,{'passmatch':False})
	else:	
		return render(request,'lib/add_admin.html',{'passmatch':True})

@onlyadmin
def add_properbooks(request):
	if(request.method=="POST"):
		sql = "INSERT INTO proper_books (bid,edition,publication_year,section) values (%s,%s,%s,%s)"
		arg=(request.POST['bid'],request.POST['edition'],request.POST['publication_year'],request.POST['section'],)
		for i in range(int(request.POST['copies'])):
			cursor.execute(sql,arg)
		mydb.commit()
		return redirect('lib:mainadmin')
	else:
		return render(request,'lib/add_properbooks.html' ,{'passmatch':False})

@onlyadmin
def show_authors(request):
	sql='select * from authors'
	cursor.execute(sql)
	result = cursor.fetchall()
	return render(request,'lib/show_authors.html',{'result':result})

@onlyadmin
def show_books(request):
	sql='select * from books'
	cursor.execute(sql)
	result = cursor.fetchall()
	return render(request,'lib/show_books.html',{'result':result})

@onlyadmin
def show_publishers(request):

DBMS_WebApp/myproject/lib/templates/lib/add_admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Staff Member</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'lib/style.css' %}"/>
</head>
<body>
    <center>
        <p align="right">
            <a href="{% url 'lib:home' %}"><input type="submit" class="submit" value="Homepage"></a>
            <a href="{% url 'lib:adminlogout' %}"><input type="submit" class="submit" value="Logout"></a>
        </p>
        <h2>Add Staff Member</h2>
        <form action="{% url 'lib:add_admin' %}" method="post">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Name:</td>
                    <td><input type="text" id="name" name="name"></td>
                </tr>
                <tr>
                    <td>UserName:</td>
                    <td><input type="text" id="username" name="username"></td>
                </tr>
                <tr>
                    <td >Password:</td>
                    <td><input type="password" id="pwd" name="pwd"  placeholder="password" value="{{request.POST.pwd}}"></td>
                </tr>
                <tr>
                    <td >Confirm Password:</td>
                    <td><input type="password" id="cpwd" name="cpwd" placeholder="confirm password" value="{{request.POST.cpwd}}"></td>
                </tr>
                {% if not passmatch %}<tr><td></td> <td style="color:red;">password did not match</td> <tr>{% endif %}

                <tr>
                    <td>Post:</td>
                    <td><input type="text" id="post" name="post"></td>
                </tr>
                <tr>
                    <td>Salary:</td>
                    <td><input type="tel" id="salary" name="salary"></td>
                </tr>
                
                <tr>
                    <td>Date of Birth:</td>
                    <td><input type="date" id="dob" name="dob"></td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td><input type="email" id="email" name="email"></td>
                </tr>
                <tr>
                    <td>Phone No 1:</td>
                    <td><input type="tel" id="phone0" name="phone0"></td>
                </tr>
                <tr>
                    <td>Phone No 2:</td>
                    <td><input type="tel" id="phone1" name="phone1"></td>
                </tr>
                <tr>
                    <tr>
                        <td >Address:</td>
                        <td><textarea name="addr" style="width:200px; height:100px;" placeholder="Address"></textarea></td>
                    </tr>
                    <tr>
                        <td>City:</td>
                        <td><input type="text" id="city" name="city"></td>
                    </tr>
                    <tr>
                        <td>Pincode:</td>
                        <td><input type="tel" id="pin" name="pin"></td>
                    </tr>
                </tr>
                <tr>
                    <td><br></td>
                </tr>
            </table>
            <table>
                <tr>
                    <center><td><input type="submit" class="submit" value="Add Admin"></td></center>
                </tr>
            </table>
        </form>
    </center>
</body>
</html>

DBMS_WebApp/myproject/lib/templates/lib/add_author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Author</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'lib/style.css' %}"/>
</head>
<body>
    <center>
        <p align="right">
            <a href="{% url 'lib:home' %}"><input type="submit" class="submit" value="Homepage"></a>
            <a href="{% url 'lib:adminlogout' %}"><input type="submit" class="submit" value="Logout"></a>
        </p>
        <h2>Add Author</h2>
        <form action="{% url 'lib:add_author' %}" method="post">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Name:</td>
                    <td><input type="text" id="name" name="name" placeholder="Name"></td>
                </tr>
                <tr>
                    <td>Date of Birth:</td>
                    <td><input type="date" id="dob" name="dob"></td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td><input type="email" id="email" name="email" placeholder="Email"></td>
                </tr>
                <tr>
                    <td>Phone No 1:</td>
                    <td><input type="tel" id="phone0" name="phone0"pattern="[0-9]*" placeholder="Phone"></td>
                </tr>
                <tr>
                    <td>Phone No 2:</td>
                    <td><input type="tel" id="phone1" name="phone1"pattern="[0-9]*" placeholder="Phone"></td>
                </tr>
                
                    <tr>
                        <td >Address:</td>
                        <td><textarea name="addr" style="width:200px; height:100px;" placeholder="Address"></textarea></td>
                    </tr>
                    <tr>
                        <td>City:</td>
                        <td><input type="text" id="city" name="city" placeholder="City"></td>
                    </tr>
                    <tr>
                        <td>PinCode:</td>
                        <td><input type="tel" id="pin" name="pin" placeholder="PinCode"></td>
                    </tr>
                
                <tr>
                    <td><br></td>
                </tr>
            </table>
            <table>
                <tr>
                    <center><td><input type="submit" class="submit" value="Add Author"></td></center>
                </tr>
            </table>
        </form>
    </center>
</body>
</html>

DBMS_WebApp/myproject/lib/templates/lib/add_publisher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Publisher</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'lib/style.css' %}"/>
</head>
<body>
    <center>
        <p align="right">
            <a href="{% url 'lib:home' %}"><input type="submit" class="submit" value="Homepage"></a>
            <a href="{% url 'lib:adminlogout' %}"><input type="submit" class="submit" value="Logout"></a>
        </p>
        <h2>Add Publisher</h2>
        <form action="{% url 'lib:add_publisher' %}" method="post">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Name:</td>
                    <td><input type="text" id="name" name="name"></td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td><input type="email" id="email" name="email"></td>
                </tr>
                <tr>
                    <td>Phone No 1:</td>
                    <td><input type="tel" id="phone0" name="phone0"></td>
                </tr>
                <tr>
                    <td>Phone No 2:</td>
                    <td><input type="tel" id="phone1" name="phone1"></td>
                </tr>
                    <tr>
                        <td >Address:</td>
                        <td><textarea name="addr" style="width:200px; height:100px;" placeholder="Address"></textarea></td>
                    </tr>
                    <tr>
                        <td>City:</td>
                        <td><input type="text" id="city" name="city"></td>
                    </tr>
                    <tr>
                        <td>Pincode:</td>
                        <td><input type="tel" id="pin" name="pin"></td>
                    </tr>
                <tr>
                    <td><br></td>
                </tr>
            </table>
            <table>
                <tr>
                    <center><td><input type="submit" class="submit" value="Add Publisher"></td></center>
                </tr>
            </table>
        </form>
    </center>
</body>
</html>

DBMS_WebApp/myproject/lib/templates/lib/add_section.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Section</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'lib/style.css' %}"/>
</head>
<body>
    <center>
        <p align="right">
            <a href="{% url 'lib:home' %}"><input type="submit" class="submit" value="Homepage"></a>
            <a href="{% url 'lib:adminlogout' %}"><input type="submit" class="submit" value="Logout"></a>
        </p>
        <h2>Add Section</h2>
        <form action="{% url 'lib:add_section' %}" method="post">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Section Name:</td>
                    <td><input type="text" id="name" name="name"></td>
                </tr>
                <tr>
                    <td>Room No.:</td>
                    <td><input type="number" id="room_no" name="room_no"></td>
                </tr>
                <tr>
                    <td>Category:</td>
                    <td><input type="text" id="category" name="category"></td>
                </tr>
                <tr>
                    <td><br></td>
                </tr>
            </table>
            <table>
                <tr>
                    <center><td><input type="submit" class="submit" value="Add Section"></td></center>
                </tr>
            </table>
        </form>
    </center>
</body>
</html>

DBMS_WebApp/myproject/lib/templates/lib/chpwd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Password</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'lib/style.css' %}"/>
</head>
<body>
    <center>
    <h2>Change Password</h2>
    
    <form action="{% url 'lib:chpwd' %}" method="post">
        {% csrf_token %}
        <table>
            <tr>
                
                <td >Password:</td>
                <td><input type="password" id="pwd" name="pwd"  placeholder="password"></td>
            </tr>
            <tr>
                <td >Confirm Password:</td>
                <td><input type="password" id="cpwd" name="cpwd" placeholder="confirm password">
                </td>
            </tr>

                {% if not passmatch %}<tr><td></td> <td style="color:red;">password did not match</td> </tr>{% endif %}

        </table>

            <table>
            <center>
            <tr>
                
            <td><input type="submit" class="submit" value="Change Password"></td>
            </tr>        
            </center>
                </table>
            </tr>
        </table>
      </form>
    </center>
</body>
</html>

DBMS_WebApp/myproject/lib/templates/lib/submitbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Submit</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'lib/style.css' %}"/>
</head>
<body>
    <center>
        <p align="right">
            <a href="{% url 'lib:home' %}"><input type="submit" class="submit" value="Homepage"></a>
            
            <a href="{% url 'lib:adminlogout' %}"><input type="submit" class="submit" value="Logout"></a>
        </p>
        <h2>Submit a Book</h2>
        <form action="{% url 'lib:submitbook' %}" method="post">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Proper Book Id:</td>
                    <td><input type="number" id="bookid" name="bid"></td>
                </tr>
                <tr>
                    <td>Book Title:</td>
                    <td><input type="text" id="booktitle" name="booktitle"></td>
                </tr>
                <tr>
                    <td>Reader Id:</td>
                    <td><input type="number" id="readerid" name="rid"></td>
                </tr>
                <tr>
                    <td>Date of Submit:</td>
                    <td><input type="date" id="submitdate" name="submitdate"></td>
                </tr>
                <tr>
                    <td>Fine(in Rupees):</td>
                    <td><input type="number" id="fine" name="fine"></td>
                </tr>
                <tr>
                    <td><br></td>
                </tr>
            </table>
            <table>
                <tr>
                    <center><td><input type="submit" class="submit" value="Submit Book"></td></center>
                </tr>
            </table>
        </form>
    </center>
</body>
</html>

DBMS_WebApp/myproject/lib/templates/lib/updateprofile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'lib/style.css' %}"/>
</head>
<body>
    <center>
    <h2>Sign Up</h2>
    <p align="right">
            <a href="{% url 'lib:chpwd' %}" type="button"><input type="submit" class="submit" value="Change Password"></a>
            <a href="{% url 'lib:home' %}"><input type="submit" class="submit" value="Homepage"></a>
    <a href="{% url 'lib:userlogout' %}" type="button"><input type="submit" class="submit" value="LogOut"></a>
    </p>
    <form action="{% url 'lib:updateprofiler' %}" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td >Name:</td>
                <td><input type="text" id="name" name="name"  placeholder="Name" value="{{userdata.name}}"></td>
            </tr>
            <tr>    
                <td >Username:</td>
                <td><input type="text" id="username" name="username"  placeholder="username" value="{{userdata.username}}"></td>
                <tr>{% if isusernameempty %}<td></td> <td style="color:red;">Username cannt be empty</td> {% endif %}
                {% if isuserexist %} <td style="color:red;">Username already exists</td> {% endif %}</tr>

            </tr>
            <tr>
                <td >Date of Birth:</td>
                <td><input type="date" id="DOB" name="dob" value="{{userdata.dob}}" ></td>
            </tr>
            <tr>
                <td >Enter your email:</td>
                <td><input type="email" id="email" name="email" value="{{userdata.email}}"></td>
            </tr>
            <tr>
                <td >Phone:</td>
                <td><input type="tel" id="phone0" name="phone0" pattern="[0-9]*" value="{{userdata.phone0}}"></td>
            </tr>
            <tr>
                <td >Phone (Optional):</td>
                <td><input type="tel" id="phone1" name="phone1" pattern="[0-9]*" value="{{userdata.phone1}}"></td>
            </tr>
            <tr>
                <td >Address:</td>
                <td><textarea name="addr" style="width:200px; height:100px;" placeholder="Address">{{userdata.addr}}</textarea></td>
            </tr>
            <tr>    
                <td >City:</td>
                <td><input type="text" id="city" name="city"  placeholder="City" value="{{userdata.city}}"></td>
            </tr>
            <tr>    
                <td >PinCode:</td>
                <td><input type="tel" id="pin" name="pin" value="{{userdata.pin}}"></td>
            </tr>
            </table>
            <table>
            <tr>
            <td><input type="submit" class="submit" value="Update"></td>
            </td>
        </table>
      </form>
      </center>
</body>
</html>